[theme]
base = "light"
primaryColor = "#ff4d6d"
backgroundColor = "#fbfaf8"
secondaryBackgroundColor = "#f5f7fb"
textColor = "#101827"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
